# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Incentive\UI\Command\UserCreateCommand:
        class: App\Incentive\UI\Command\UserCreateCommand
        arguments:
            $commandBus: '@broadway.command_handling.command_bus'
        tags:
            - { name: 'console.command' }

    App\Incentive\UI\Command\DeliveryCompleteCommand:
        arguments:
            $commandBus: '@broadway.command_handling.command_bus'
        tags:
            - { name: 'console.command' }


    App\Common\Infrastructure\Cmd\CreateEventStoreCommand:
        arguments:
            $connection: "@doctrine.dbal.default_connection"
            $eventStore: '@broadway.event_store'
        tags:
            - { name: 'console.command' }


    App\Incentive\Infrastructure\Repository\EventStore\EventStoreUserRepository:
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            -
                - '@broadway.metadata_enriching_event_stream_decorator'

    App\Incentive\Domain\User\CommandHandler\RegisterUserHandler:
        arguments:
            $userRepository: '@App\Incentive\Infrastructure\Repository\EventStore\EventStoreUserRepository'
        tags:
            - { name: 'broadway.command_handler' }

    App\Incentive\Domain\User\CommandHandler\DeliveryCompleteHandler:
        arguments:
            $userRepository: '@App\Incentive\Infrastructure\Repository\EventStore\EventStoreUserRepository'
            $deliveryBonusPoints: 1
        tags:
            - { name: 'broadway.command_handler' }


